// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ7vHbyuHeM30ikdIEKI1MC_5yjfkF1nY',
    appId: '1:831367630091:web:654d4c6aab41b7aee6a60e',
    messagingSenderId: '831367630091',
    projectId: 'partia-d71e4',
    authDomain: 'partia-d71e4.firebaseapp.com',
    storageBucket: 'partia-d71e4.appspot.com',
    measurementId: 'G-KCSMH619QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKj3UnkO-wHia4DMpYNPg9eFd6e9c77hU',
    appId: '1:831367630091:android:abec3e0bc4234352e6a60e',
    messagingSenderId: '831367630091',
    projectId: 'partia-d71e4',
    storageBucket: 'partia-d71e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5yqgSZtwO8peBKoCTlIdd6lT9XcpWCQA',
    appId: '1:831367630091:ios:10c06c6236ceef62e6a60e',
    messagingSenderId: '831367630091',
    projectId: 'partia-d71e4',
    storageBucket: 'partia-d71e4.appspot.com',
    iosBundleId: 'com.partia.partIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5yqgSZtwO8peBKoCTlIdd6lT9XcpWCQA',
    appId: '1:831367630091:ios:10c06c6236ceef62e6a60e',
    messagingSenderId: '831367630091',
    projectId: 'partia-d71e4',
    storageBucket: 'partia-d71e4.appspot.com',
    iosBundleId: 'com.partia.partIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ7vHbyuHeM30ikdIEKI1MC_5yjfkF1nY',
    appId: '1:831367630091:web:066c54e7180f7d1be6a60e',
    messagingSenderId: '831367630091',
    projectId: 'partia-d71e4',
    authDomain: 'partia-d71e4.firebaseapp.com',
    storageBucket: 'partia-d71e4.appspot.com',
    measurementId: 'G-Z1P5MH5TJR',
  );
}
